### ISSUE TITLE
Log in using browser back button

### ISSUE THREAD

**Issue by nikolajreiser** [zchristianl/corpse-test#19]
After logging out of a client account (using the logout button), it is possible to view the account home page again by using the back button of the browser. This returns to the client home view, without needing the user to specify the login credentials.

Severity: Medium

Since this problem may be platform specific here are the browsers and OS used where the problem occurred:
OS: macOS 10.15.1
Safari: Version 13.03
Chrome: Version 78.0.3904.108

Also note that no actions can be performed on the client home page when using the browser back button to navigate there after logging out, as clicking any of the buttons (like New Order) opens the login page, forcing the user to log in if they wish to use the account.

**Comment by zchristianl** [comment]
This can happen on any website. It's a matter of deciding what can be cached and how long it may be cached for. Since the deadline for this project is imminent and caching is beneficial to the performance of our platform, we're not going to take any further action. Even if the individual goes back a page, they won't be able to do anything, aside from viewing the data they've already seen, because they're logged out and will be prompted to login again.
